delete from osm.forts;
insert into osm.forts select * from osm.forts_c;
delete from osm.cemetery;
insert into osm.cemetery select * from osm.cemetery_c;
delete from osm.buildings;
insert into osm.buildings select * from osm.buildings_c;
delete from osm.settlements;
insert into osm.settlements select * from osm.settlements_c;
delete from osm.water;
insert into osm.water select * from osm.water_c;
delete from osm.water_line;
insert into osm.water_line select * from osm.water_line_c;
delete from osm.bridges;
insert into osm.bridges select * from osm.bridges_c;
delete from osm.regions;
insert into osm.regions select * from osm.regions_c;
delete from osm.parks;
insert into osm.parks select * from osm.parks_c;
delete from osm.reserve_parks;
insert into osm.reserve_parks select * from osm.reserve_parks_c;
delete from osm.square;
insert into osm.square select * from osm.square_c;
delete from osm.railway_platform;
insert into osm.railway_platform select * from osm.railway_platform_c;
delete from osm.island;
insert into osm.island select * from osm.island_c;
delete from osm.highways;
insert into osm.highways select * from osm.highways_c;
delete from osm.roads;
insert into osm.roads select * from osm.roads_c;
delete from osm.milestone_point;
insert into osm.milestone_point select * from osm.milestone_point_c;